### ISSUE TITLE
Add credit to Whitespace?

### ISSUE THREAD

**Issue by jeremydouglass** [BaseMax/DotWhitespace#1]
The illustration on this repo is taken from the Wikipedia page for [Whitespace](https://en.wikipedia.org/wiki/Whitespace_(programming_language)) -- a language created by Brady and Morris around 2003. But the README says "DotWhitespace is an esoteric programming language developed by Max Base. It was released on 17 July 2020."

Even if dotwhitespace is different, please consider crediting what inspired it in your README and explaining the differences, if any -- especially if you are showing output taken directly from other [whitespace-language](https://github.com/topics/whitespace-language) interpreters.

**Comment by BaseMax** [comment]
Hi Jeremy Douglass,

Thanks for your message. Yeah, you are right.
I'm wait for preparing own image for repository.

**Comment by BaseMax** [comment]
I would be grateful if you could guide me through this. @jeremydouglass 
I am a student.
https://github.com/BaseMax/DotWhitespace#acknowledgments

**Comment by jeremydouglass** [comment]
Hi Max,

I hope you are well. Not a licensing issue -- I would just suggest using a different picture when you can, and adding a credit to the inspiration. I see that you already added this:

> The grammar idea for this language was first taken from Whitespace, but these have nothing to do with each other and are different in many ways.

I would suggest something that gives people more information. For example.

> This language was inspired by [Whitespace](https://en.wikipedia.org/wiki/Whitespace_(programming_language)). However DotWhitespace is not a whitespace interpreter, and the grammar is different in many ways. For example:

And then say what is different about your language! People will find that interesting. I'm curious. I'm guessing that it also has dots, for example....

**Comment by BaseMax** [comment]
Thanks, I will apply this changes.

**Comment by BaseMax** [comment]
Can i email you about a cooperation?
I am going to write an article to introduce this project.
I think we can do it together, Can i get help from you?
I'm not a good writer in English :(
And you, as a powerful writer, guide me in this direction.
Finally we can publish in a magazine.

**Comment by BaseMax** [comment]
Hello,
Just an update for this issue:
Finally, we designed a logo / shape for this project.
Thanks to "Farzad Fazayeli", one of my good friends for his help.

## Concepts Design
![1](https://user-images.githubusercontent.com/2658040/91645330-7be7d000-ea59-11ea-8379-5ab1479a1efe.jpg)
![2](https://user-images.githubusercontent.com/2658040/91645331-7db19380-ea59-11ea-902b-a5e5951a296a.jpg)
![3](https://user-images.githubusercontent.com/2658040/91645332-7e4a2a00-ea59-11ea-9fd9-114010ea7f30.jpg)
![4](https://user-images.githubusercontent.com/2658040/91645334-7ee2c080-ea59-11ea-8893-f3861831f4b9.png)
![5](https://user-images.githubusercontent.com/2658040/91645335-8013ed80-ea59-11ea-9830-ca645366b0ba.jpg)
![6](https://user-images.githubusercontent.com/2658040/91645336-80ac8400-ea59-11ea-8c8e-73855eb61ba5.jpg)
![7](https://user-images.githubusercontent.com/2658040/91645337-81451a80-ea59-11ea-9246-b9c199e11944.jpg)
![8](https://user-images.githubusercontent.com/2658040/91645338-81ddb100-ea59-11ea-927f-b4c07dbeb5b3.jpg)

## Final design

![9](https://user-images.githubusercontent.com/2658040/91645428-35df3c00-ea5a-11ea-822c-99c45928d451.jpg)
![10](https://user-images.githubusercontent.com/2658040/91645430-37a8ff80-ea5a-11ea-964c-09f218c2a373.png)

Regards,
Max

**Comment by BaseMax** [comment]
Hi Sir @jeremydouglass,

Please, Can i email you about a cooperation?

I am going to write an article to introduce this project. (Scientific Paper)
I think we can do it together, Can i get help from you?
I'm not a good writer in English :(
And you, as a powerful writer, guide me in this way.
Finally we can publish in a magazine or scientific journals.

Thanks in advance.

**Comment by jeremydouglass** [comment]
@BaseMax congratulations on your logo design, and good luck with this project.

Unfortunately I cannot write a paper with you on your project, and I won't be able to help you with your English writing. However, if you do write a paper about your project then I would be happy to take a quick look and give you feedback on your ideas, if you wish. best regards -- Jeremy
